Revert "Fallback to 2G only"
ubports/ofono pull request #11
Opened 2020-01-02 00:22 UTC by dobey

This reverts commit 0ca1960b60ba8585f121aff4bfb5e64c58aa96e0.

This change was a hacky workaround to solve an issue that apparently is only an issue on dual SIM devices, but breaks support for CDMA on devices that do support it.

2020-01-22 18:06 UTC, UniversalSuperBox commented
Merging this would likely fix CDMA support on the Nexus 5, but it causes problems on the Meizu Pro 5. Namely, it always falls back to 2G for both SIMs on every boot. Unless these can be fixed in unison, I don't think we should merge this. Even if it was a hack that shouldn't have been merged in the first place.

2020-01-23 01:13 UTC, dobey commented
I don't have a Pro 5, nor any time to try and figure out why it's broken, and it's already an incredibly difficult device to keep supporting, being the only Exynos based OEM Ubuntu Edition device, and with multiple models. So I guess this should just be closed.

2020-03-10 19:34 UTC, dobey commented
I've pushed a new commit, which checks the modem vendor, and only forces GSM for MTK based devices. This should at least get CDMA working again on the other phones that support it, while working around the weird issue on the Pro 5 by forcing GSM there.

2020-07-15 17:11 UTC, UniversalSuperBox requested changes
In its current state, this causes the Pro 5 to fail to restore its settings

2020-10-08 14:42 UTC, dobey commented
Closing this as it didn't solve the problem.

2020-10-08 14:42 UTC, closed without merging