Add basic parts to support LTE_CA RAT information
ubports/ofono pull request #18
Opened 2021-02-04 21:51 UTC by Flohack74

See also https://git.sailfishos.org/mer-core/ofono/commit/c1156320acd67b8e1afeeb1c5ed581262f2edc66 - we are basically mapping LTE_CA to LTE for the moment. It would be perfectly okay to expose that information in the correct way to the consumers, and add a new ACCESS_TECHNOLOGY enum member for this.

2021-02-08 10:02 UTC, peat-psuwit requested changes

2021-02-08 10:02 UTC, peat-psuwit commented on plugins/u8500.c
> +		break;
I don't think we're supposed to put `break` here.
https://git.kernel.org/pub/scm/network/ofono/ofono.git/tree/plugins/u8500.c#n130

Although, we don't use this plugin anyway. What if we just disable building it?

2021-02-08 10:35 UTC, Flohack74 commented on plugins/u8500.c
> +		break;
Ok I will fix it. Well we can disable it, too, but I think fixing a compile issue even for disabled code is a god thing :)

2021-03-28 22:31 UTC, mariogrip commented
So LTE_CA is LTE+, but do we have any devices with this version of ofono that support LTE+?  

https://github.com/aosp-mirror/platform_frameworks_base/blob/c5d02da0f6553a00da6b0d833b67d3bbe87341e0/packages/SystemUI/src/com/android/systemui/statusbar/policy/MobileSignalController.java#L271

2021-03-31 17:06 UTC, Flohack74 commented
Yeah thats a good question, I really dont know. Also, you need a matching carrier :) I will do a quick review what devices could have it.

2021-03-31 17:37 UTC, Flohack74 commented
![grafik](https://user-images.githubusercontent.com/16186470/113186778-5b366180-9258-11eb-85c9-5f8541c63e94.png)

![grafik](https://user-images.githubusercontent.com/16186470/113186812-66898d00-9258-11eb-8bcc-7fd5d5471bb2.png)

![grafik](https://user-images.githubusercontent.com/16186470/113186878-786b3000-9258-11eb-9595-804dc1f89253.png)

Plenty of options ;)

2022-05-30 16:56 UTC, fredldotme approved these changes
LGTM

2022-05-30 19:30 UTC, peat-psuwit approved these changes

2022-05-30 19:34 UTC, merged